name: Deploy master
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install
